// Generates src/abi.ts (ABIs as `const` for viem type inference) and test/fixtures/bytecode.json
// from the Foundry build output. Run `forge build` in ../contracts first.
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "contracts", "out");
if (!existsSync(join(out, "PassportGate.sol"))) {
  console.error("No Foundry build output in contracts/out — run `forge build` in contracts/ first.");
  process.exit(1);
}
const contracts = {
  AgentIdentityRegistry: "AgentIdentityRegistry.sol",
  AgentReputationRegistry: "AgentReputationRegistry.sol",
  AgentValidationRegistry: "AgentValidationRegistry.sol",
  CredentialStatusRegistry: "CredentialStatusRegistry.sol",
  PassportGate: "PassportGate.sol",
  GroundedFeedback: "GroundedFeedback.sol",
  PasskeyAccountFactory: "PasskeyAccount.sol",
  PasskeyAccount: "PasskeyAccount.sol",
  MockToken: "MockToken.sol",
  PassportDex: "PassportDex.sol",
  PassportMerchant: "PassportMerchant.sol",
};

let ts = "// Generated by scripts/gen-abi.mjs from the Foundry build. Do not edit.\n\n";
const bytecode = {};
for (const [name, file] of Object.entries(contracts)) {
  const artifact = JSON.parse(readFileSync(join(out, file, `${name}.json`), "utf8"));
  const abiName = name[0].toLowerCase() + name.slice(1) + "Abi";
  ts += `export const ${abiName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
  bytecode[name] = artifact.bytecode.object;
}
writeFileSync(join(here, "..", "src", "abi.ts"), ts);
mkdirSync(join(here, "..", "test", "fixtures"), { recursive: true });
writeFileSync(join(here, "..", "test", "fixtures", "bytecode.json"), JSON.stringify(bytecode));
console.log(`abi.ts: ${Object.keys(contracts).length} contracts`);
